openapi: "3.0.0"
info:
  description: Just a test
  version: "1.0.0"
  title: Shopping List
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: a@bc.de
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /items:
    get:
      summary: Get all items
      operationId: getAllItems
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
    post:
      summary: Add a new item
      operationId: addItem
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        200:
          description: OK
          
  /items/{id}:
    delete:
      summary: Delete an item
      operationId: deleteItemById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Deleted
        '401':
          description: Unauthorized
        '404':
          description: Not found

components:
  schemas:
    Item:
      type: object
      required:
        - id
        - itemlabel
      properties:
        id:
          type: integer
          format: int64
        itemlabel:
          type: string

